function createBasicNetwork() {
    createRouterObject(500, 400);
    setRouterIps(getLastElement(".router.item-dropped"), "192.168.1.1/24", "193.168.1.1/24", "172.16.1.1/24");
    createSwitchObject(300, 550);
    createConn(getLastElement(".router.item-dropped"), getLastElement(".switch.item-dropped"));
    createPcObject(200, 700);
    createDhcpRelayObject(100, 600);
    createConn(getLastElement(".dhcp-relay.item-dropped"), getLastElement(".switch.item-dropped"));
    createConn(getLastElement(".pc.item-dropped"), getLastElement(".switch.item-dropped"));
    createSwitchObject(300, 300);
    createConn(getLastElement(".router.item-dropped"), getLastElement(".switch.item-dropped"));
    createDhcpServerObject(100, 300);
    createConn(getLastElement(".dhcp-server"), getLastElement(".switch.item-dropped"));
    createSwitchObject(700, 300);
    createConn(getLastElement(".router.item-dropped"), getLastElement(".switch.item-dropped"));
    createRouterObject(600, 150);
    setRouterIps(getLastElement(".router.item-dropped"), "172.16.1.2/24", "194.168.1.1/24");
    createConn(getLastElement(".router.item-dropped"), getLastElement(".switch.item-dropped"));
    createSwitchObject(900, 150);
    createPcObject(1100, 125);
    createConn(getLastElement(".pc.item-dropped"), getLastElement(".switch.item-dropped"));
    createConn(getLastElement(".router.item-dropped"), getLastElement(".switch.item-dropped"));
    createRouterObject(1000, 300);
    setRouterIps(getLastElement(".router.item-dropped"), "192.168.1.1/24", "193.168.1.1/24", "172.16.1.1/24");
    createConn(getLastElement(".router.item-dropped"), getLastElement(".switch.item-dropped", -2));
    createRouterObject(700, 500);
    setRouterIps(getLastElement(".router.item-dropped"), "192.168.1.1/24", "193.168.1.1/24", "172.16.1.1/24");
    createConn(getLastElement(".router.item-dropped"), getLastElement(".switch.item-dropped", -2));
    createSwitchObject(600, 600);
    createPcObject(550, 725);
    createConn(getLastElement(".pc.item-dropped"), getLastElement(".switch.item-dropped"));
    createConn(getLastElement(".router.item-dropped"), getLastElement(".switch.item-dropped"));
    createSwitchObject(1200, 225);
    createConn(getLastElement(".router.item-dropped", -2), getLastElement(".switch.item-dropped"));
    createSwitchObject(1000, 500);
    createConn(getLastElement(".router.item-dropped", -2), getLastElement(".switch.item-dropped"));
    createRouterObject(1400, 225);
    setRouterIps(getLastElement(".router.item-dropped"), "192.168.1.1/24", "193.168.1.1/24", "172.16.1.1/24");
    createConn(getLastElement(".router.item-dropped"), getLastElement(".switch.item-dropped", -2));
    createSwitchObject(1600, 225);
    createPcObject(1750, 180);
    createConn(getLastElement(".router.item-dropped"), getLastElement(".switch.item-dropped"));
    createConn(getLastElement(".pc.item-dropped"), getLastElement(".switch.item-dropped"));
    createRouterObject(1200, 550);
    setRouterIps(getLastElement(".router.item-dropped"), "192.168.1.1/24", "193.168.1.1/24", "172.16.1.1/24");
    createConn(getLastElement(".router.item-dropped"), getLastElement(".switch.item-dropped", -2));
    createSwitchObject(1400, 450);
    createSwitchObject(1400, 650);
    createDnsServerObject(1600, 450);
    createDnsServerObject(1600, 650);
    createConn(getLastElement(".router.item-dropped"), getLastElement(".switch.item-dropped"));
    createConn(getLastElement(".router.item-dropped"), getLastElement(".switch.item-dropped", -2));
    createConn(getLastElement(".dns-server.item-dropped"), getLastElement(".switch.item-dropped"));
    createConn(getLastElement(".dns-server.item-dropped", -2), getLastElement(".switch.item-dropped", -2));
    //anotaciones de texto
    createTextObject(150, 475);
    getLastElement(".text-annotation").querySelector("input").value = "192.168.1.0/24";
    createTextObject(200, 225);
    getLastElement(".text-annotation").querySelector("input").value = "193.168.1.0/24";
    createTextObject(450, 275);
    getLastElement(".text-annotation").querySelector("input").value = "172.16.1.0/16";
    createTextObject(800, 75);
    getLastElement(".text-annotation").querySelector("input").value = "194.168.1.0/24";
    createTextObject(450, 500);
    getLastElement(".text-annotation").querySelector("input").value = "10.0.0.0/8";
    createTextObject(1175, 150);
    getLastElement(".text-annotation").querySelector("input").value = "194.168.1.0/24";
    createTextObject(1500, 150);
    getLastElement(".text-annotation").querySelector("input").value = "12.0.0.0/8";
    createTextObject(800, 500);
    getLastElement(".text-annotation").querySelector("input").value = "13.0.0.0/8";
    createTextObject(1300, 350);
    getLastElement(".text-annotation").querySelector("input").value = "1.0.0.0/8";
    createTextObject(1300, 700);
    getLastElement(".text-annotation").querySelector("input").value = "8.0.0.0/8";
}